[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
; Enable USB CDC on Boot if the C3 board uses native USB
build_flags = 
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1

; If you need specific libraries for parsing the Lidar data later, we can add them here:
; lib_deps = 
